apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ .Release.Name }}
spec:
  groups:
  - name: {{ .Release.Name }}
    rules:
    - alert: TooMany502Errors
      annotations:
        summary: High number of HTTP 502 errors
      expr: '100 * (sum by(instance) (rate(http_requests_total{namespace="{{ .Release.Name }}",code="502"}[5m])) / sum by(instance) (rate(http_requests_total{namespace="{{ .Release.Name }}"}[5m]))) > 10'
      for: 1m
      labels:
        app: {{ .Release.Name  }}
        severity: critical
        team: {{ .Values.chiaretto.team  }}
