apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ .Release.Name }}
spec:
  groups:
  - name: example
    rules:
    - alert: VersionAlert
      expr: version{job="{{ .Release.Name }}"} == 0
