apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ .Release.Name }}
spec:
  groups:
  - name: {{ .Release.Name }}
    rules:
    - alert: TooMany502Errors
      expr: 100 * (sum by(instance) (rate(http_requests_total{namespace="{{ .Release.Name }}",code="502"}[5m])) / sum by(instance) (rate(http_requests_total{namespace="{{ .Release.Name }}"}[5m]))) > 10
