apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}
  labels:
    team: chiaretto
    app: prometheus
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  endpoints:
  - port: "8080-tcp"
    path: /metrics
  selector:
    matchLabels:
      app: prometheus
