apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: chiaretto-app
  labels:
    team: chiaretto
    app: prometheus
spec:
  selector:
    matchLabels:
      app: chiaretto-app
  endpoints:
  - port: "8081-tcp"
    path: /metrics
  selector:
    matchLabels:
      app: prometheus
